AllCops:
  Exclude:
    - 'lib/has_a_token/version.rb'
    - 'Guardfile'
  DisplayStyleGuide: true
  RunRailsCops: true

Metrics/LineLength:
  Max: 100

Style/AndOr:
  EnforcedStyle: conditionals

Style/EmptyElse:
  EnforcedStyle: empty

Style/IndentationConsistency:
  EnforcedStyle: normal

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Max: 200 # lenient

Metrics/ModuleLength:
  Max: 200 # lenient

Style/CommandLiteral:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false
  EnforcedStyle: double_quotes
